# Generated by Django 4.0.5 on 2022-08-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionArtesania',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('artesania', models.CharField(max_length=100, verbose_name='Nom Artesania')),
                ('opinion', models.TextField(verbose_name='Opinión')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Opinion de Artesania',
                'verbose_name_plural': 'Opiniones de Artesanias',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='artesanias',
            options={'ordering': ['-created'], 'verbose_name': 'Artesania', 'verbose_name_plural': 'Artesanias'},
        ),
        migrations.AlterField(
            model_name='artesanias',
            name='descripcion',
            field=models.TextField(max_length=500, verbose_name='Descripción general'),
        ),
        migrations.AlterField(
            model_name='artesanias',
            name='nombre',
            field=models.TextField(max_length=20, verbose_name='Nombre Artesania'),
        ),
    ]
